### PR TITLE
Add Color Picker to DynText Modifier

### PR DESCRIPTION
**Pull request by DoobesURU**
Small addition to the Localized/DynText modifier to add a color picker for the font color in the font options. Utilizes the existing `font_color` def in properties.

### CODE REVIEW

**Comment by DoobesURU** [comment]
Just realized export isn't working just yet, so converted to draft until I do. 😊

**Comment by DoobesURU** [comment]
Looks like it wasn't anything I did, but an issue with Korman itself: #418

**Review by Hoikas — APPROVED** [review]
Is this ready to go?

**Comment by DoobesURU** [comment]
> Is this ready to go?

Should be! Just one line of code to add a color picker below the other two font options.

**Review by Hoikas — APPROVED** [review]

**Pull request merged**
