### PR TITLE
Update convert.py

### PR DESCRIPTION
**Pull request by TikiBear**
Fix overwritten "layers = pages paradigm" default pages.

### CODE REVIEW

**Comment by dpogue** [comment]
I think I would argue that most people don't use Blender layers for different Plasma pages. If anything, it's more likely people would use Blender scenes (although those are slightly annoying to work with).

Speaking for myself, I use Blender layers to group different types of objects: geometry in one layer; colliders and regions in another; lamps in another; OneShotMods, sound emitters, and spawn points in another; etc.

**Comment by Deledrius** [comment]
I agree with @dpogue.  That's how I use layers in Blender with korman as well.

**Comment by TikiBear** [comment]
I don't know the originator of this. I wondered if it might be obsolete now. It's still present in the initialization code.
 
 
-----Original Message-----

**Comment by Deledrius** [comment]
> I don't know the originator of this. I wondered if it might be obsolete now. It's still present in the initialization code.
@Hoikas can elaborate, but as I understand it there was an intent to support that model initially but it has not been the case for some time.

**Pull request closed without merging**
